inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# Don't worry about missing frozen string literal comment
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails