language: ruby
services:
  - postgresql
sudo: false
cache: bundler
env:
  - DEVISE_SECRET=c0ffee MAIL_SERV=example.com MAIL_PORT=587 MAIL_DOM=example.com MAIL_USER=foo MAIL_PASS=foo ADMIN_EMAIL=foo@example.com SOCIETY_EMAIL="CLOGS <clogs@example.com>"
install:
  - bundle install
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database clogs_db_test' -U postgres
script:
  - bin/rails db:schema:load spec RAILS_ENV=test
