language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
env:
  - DEVISE_SECRET=c0ffee MAIL_SERV=example.com MAIL_PORT=587 MAIL_DOM=example.com MAIL_USER=foo MAIL_PASS=foo ADMIN_EMAIL=foo@example.com SOCIETY_EMAIL="CLOGS <clogs@example.com>"
before_install:
  - rm Gemfile.lock
script:
  - RAILS_ENV=test xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rake db:migrate spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database clogs_db_test' -U postgres
